# Generated by Django 5.0.6 on 2024-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
