# Generated by Django 5.0.6 on 2024-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='selection',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
