# Generated by Django 5.0.6 on 2024-07-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BugTrackerTickets',
            new_name='BugTrackerTicket',
        ),
        migrations.RenameModel(
            old_name='TestCaseFiles',
            new_name='TestCaseFile',
        ),
        migrations.RenameModel(
            old_name='TestCaseResults',
            new_name='TestCaseResult',
        ),
        migrations.RenameModel(
            old_name='TestCaseResultFiles',
            new_name='TestCaseResultFile',
        ),
        migrations.RenameModel(
            old_name='TestCaseTickets',
            new_name='TestCaseTicket',
        ),
        migrations.RenameModel(
            old_name='TestPlanFiles',
            new_name='TestPlanFile',
        ),
        migrations.RenameModel(
            old_name='TestRunFiles',
            new_name='TestRunFile',
        ),
        migrations.RenameModel(
            old_name='TestSuiteFiles',
            new_name='TestSuiteFile',
        ),
    ]
