# Generated by Django 5.0.6 on 2024-08-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0002_alter_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='action_message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_object',
            field=models.CharField(choices=[('TestCase', 'Testcase'), ('TestCaseResult', 'Testcase Result'), ('Section', 'Section'), ('TestSuite', 'Test Suite'), ('TestRun', 'Test Run'), ('TestPlan', 'Test Plan'), ('Milestone', 'Milestone'), ('Project', 'Project')], max_length=255),
        ),
    ]
