# Generated by Django 5.0.6 on 2024-07-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0003_remove_testcaseresult_status_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='number_of_sections',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_suite_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testruns', to='tcms.testsuite'),
        ),
    ]
