# Generated by Django 5.0.6 on 2024-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0006_alter_testcase_latest_result_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='number_of_passed_test_cases',
        ),
        migrations.RemoveField(
            model_name='section',
            name='number_of_test_cases',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='number_of_blocked_test_cases',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='number_of_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='number_of_failed_test_cases',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='number_of_partial_test_cases',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='number_of_untested_test_cases',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
