# Generated by Django 5.0.6 on 2024-07-30 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0008_rename_number_of_comments_testsuite_testcase_latest_result_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='milestone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testruns', to='tcms.milestone'),
        ),
        migrations.AlterField(
            model_name='testruntestcaseresults',
            name='test_run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='tcms.testrun'),
        ),
    ]
