# Generated by Django 5.0.6 on 2024-07-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0009_alter_testrun_creator_id_alter_testrun_milestone_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testruntestcaseresults',
            name='test_run_test_case_id',
        ),
        migrations.RemoveField(
            model_name='testruntestcaseresults',
            name='test_case_result_id',
        ),
        migrations.RemoveField(
            model_name='testruntestcaseresults',
            name='test_run_id',
        ),
        migrations.AddField(
            model_name='testrun',
            name='test_case_filter_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_case_filter',
            field=models.CharField(choices=[('ALL', 'ALL'), ('SELECTED', 'SELECTED'), ('REGEX_ON_NAME', 'REGEX_ON_NAME')], default='ALL', max_length=255),
        ),
        migrations.CreateModel(
            name='TestRunTestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcms.testcase')),
                ('test_case_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcms.testcaseresult')),
                ('test_run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='tcms.testrun')),
            ],
        ),
        migrations.DeleteModel(
            name='TestRunTestCase',
        ),
        migrations.DeleteModel(
            name='TestRunTestCaseResults',
        ),
    ]
