# Generated by Django 5.0.6 on 2024-07-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms', '0011_alter_testcaseresult_result_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='number_of_passed_test_cases',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
